### ISSUE TITLE
Incremental Data Sync Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#10]
### Incremental Data Synchronization from MySQL to Postgres with Airbyte.

Configure Airbyte to perform incremental data synchronization from MySQL to Postgres, optimizing for data freshness and reducing the load on source and destination systems.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by avirajsingh7** [comment]
@ThaliaBarrera can I work on this one?

**Comment by ThaliaBarrera** [comment]
Hi @avirajsingh7! Sure, I have assigned you to it.

**Comment by ThaliaBarrera** [comment]
Hi @avirajsingh7, this message is just to remind you that according to the Hackathon rules you have 5 days to submit progress on the issue. I’ll give you a couple more days to submit a PR, otherwise I’ll have to mark the issue as “To be Claimed” or reassign it. 

Thank you for understanding! Let me know if you have any questions.

**Comment by avirajsingh7** [comment]
@ThaliaBarrera busy with my exam for this week, I will continue from monday, if you allow

**Comment by ThaliaBarrera** [comment]
Sorry @avirajsingh7! I need to reassign this issue so others can contribute as well. Let me know once you're free and if you'd like to take another issue :).

**Comment by bishalbera** [comment]
Hello @ThaliaBarrera I've  submitted a  [PR](https://github.com/airbytehq/quickstarts/pull/59) and next I want to work on this. Can I? :)

**Comment by bishalbera** [comment]
@ThaliaBarrera actually I needed more info . like I think i dont need to implement dbt and dagster!! only through the terraform i have to perform incremental sync . is that right?? thats why I deleted my  comment 😅

**Comment by ThaliaBarrera** [comment]
> @ThaliaBarrera actually I needed more info . like I think i dont need to implement dbt and dagster!! only through the terraform i have to perform incremental sync . is that right?? thats why I deleted my comment 😅

Yeah, exactly @bishalbera, just configuring the Airbyte connection to be incremental
