### ISSUE TITLE
Low-Latency Data Availability Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#14]
### Achieving Low-Latency Data Availability with Logical Replication from Postgres using Airbyte.

Configure Airbyte with logical replication to facilitate low-latency data availability from a Postgres database, ensuring near real-time data access and enhancing responsiveness for analytical queries and applications.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by cannarron** [comment]
Hello @ThaliaBarrera I'd like to give a shot a this, please assign me

**Comment by ThaliaBarrera** [comment]
Hi @cannarron! Sure, I have assigned it to you.

**Comment by ThaliaBarrera** [comment]
Hi @cannarron, this message is just to remind you that according to the Hackathon rules you have 5 days to submit progress on the issue. I’ll give you a couple more days to submit a PR, otherwise I’ll have to mark the issue as “To be Claimed” or reassign it. 

Thank you for understanding! Let me know if you have any questions.

**Comment by ThaliaBarrera** [comment]
Hi @cannarron, by PR I mean opening a pull request to the repo. You can check the ones that have been submitted and merged before. The instructions are in the README. 

Let me know if you have questions!

**Comment by ThaliaBarrera** [comment]
I am unassigning this issue as there has been no progress in the last 5 days. This is now open!

**Comment by sowmiyaksr** [comment]
@ThaliaBarrera : can you please assign this to me?

**Comment by ThaliaBarrera** [comment]
Hi @sowmiyaksr! Sure, I have assigned it to you. Let me know if you have questions.

**Comment by sowmiyaksr** [comment]
@ThaliaBarrera : is "Low latency Data Availability Stack" can be created using CDK?

**Comment by ThaliaBarrera** [comment]
> @ThaliaBarrera : is "Low latency Data Availability Stack" can be created using CDK?

Hi @sowmiyaksr! The idea of the quickstarts is to use existing Airbyte connectors via the UI or Terraform, so the CDK wouldn't apply here. What did you want to use the CDK for?

**Comment by ThaliaBarrera** [comment]
I'm unassigning this issue since there has been no progress in the last 5 days. Let me know if you still want to work on this @sowmiyaksr, otherwise, it's to be claimed.

**Comment by topefolorunso** [comment]
Can I pick this up @ThaliaBarrera

**Comment by ThaliaBarrera** [comment]
Sure @topefolorunso!
