### ISSUE TITLE
Customer Segmentation Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#17]
### Building Customer Segments with E-commerce Data.

Extract customer interaction and transaction data from e-commerce platforms using Airbyte and dbt to create detailed customer segments for personalized marketing.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by sarojregmi200** [comment]
I want to work on this quickstart, I am new to Airbyte but I understand the requirements of this quickstart and will try my best to build it.

Can I be assigned to this project?

**Comment by ThaliaBarrera** [comment]
Hi @sarojregmi200! Sure, I have assigned you to this quickstart.

**Comment by pritipsingh** [comment]
Hey @ThaliaBarrera can I please take this up?

**Comment by pritipsingh** [comment]
Hey @ThaliaBarrera pinging again if I can take this up?

**Comment by sarojregmi200** [comment]
@pritipsingh, sure no worries. I will let you know if i wanted to contribute to other issues.

**Comment by bishalbera** [comment]
@ThaliaBarrera  Hello hope you are doing well  :) , if you are done reviewing my [PR](https://github.com/airbytehq/quickstarts/pull/75)  next I would like to work on this. Ty

**Comment by ThaliaBarrera** [comment]
@bishalbera Yes, sure!
