### ISSUE TITLE
Airbyte, dbt and Airflow (ADA) Stack with BigQuery

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#2]
### Continuous Data Synchronization with Airbyte, dbt, and Apache Airflow.

Utilize Airbyte and dbt for data extraction and transformation, and implement Apache Airflow to orchestrate continuous data synchronization workflows for always-up-to-date data.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by 1cadumagalhaes** [comment]
I could work on this

**Comment by ThaliaBarrera** [comment]
> I could work on this

Thanks @1cadumagalhaes, I have assigned it to you!

**Comment by 1cadumagalhaes** [comment]
Hey @ThaliaBarrera , thanks
 I'll submit them today, I got a little lost with the deadline but it's okay, thanks for the extra days

**Comment by topefolorunso** [comment]
👀

**Comment by ThaliaBarrera** [comment]
Hi @1cadumagalhaes! Let me know how you’re progressing with this, and if you have any questions.
