### ISSUE TITLE
Shopping Cart Analysis Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#24]
### Analyzing Shopping Cart Abandonment with E-commerce Data.

Extract shopping cart data from e-commerce platforms using Airbyte and dbt, analyze user behavior, and devise strategies to reduce cart abandonment rates.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by NARUDESIGNS** [comment]
Hello @ThaliaBarrera I'd like to work on this.

**Comment by ThaliaBarrera** [comment]
Hi @NARUDESIGNS! Sure, I have assigned it to you.

**Comment by NARUDESIGNS** [comment]
Ok, thank you! @ThaliaBarrera 
I'll reach out if I have any questions :)

**Comment by NARUDESIGNS** [comment]
Hello @ThaliaBarrera thanks for the reminder, I didn't know that. 
I'm new to the data field hence the delay, so I sincerely appreciate the time extension.

Thank you!

**Comment by ThaliaBarrera** [comment]
Hi @NARUDESIGNS! Do you think you’ll be able to complete this quickstart? Let me know if you have questions.

**Comment by NARUDESIGNS** [comment]
Hello @ThaliaBarrera thank you very much for your patience. I admit I will not be able to make this fix at this time due to my knowledge gap.
Please feel free to reassign this issue to someone else and hopefully in future, I can come back to try a new issue.

**Comment by bryanspacex** [comment]
Hello @ThaliaBarrera I'd like to work on this.
Also may I know where should I be submitting the code .

**Comment by ThaliaBarrera** [comment]
Hi @bryanspacex! I have assigned it to you. You can check the instructions for submitting a PR in the README of this repo. Let me know if you have any other questions.

**Comment by bryanspacex** [comment]
Ok thnx, will check it out

**Comment by ThaliaBarrera** [comment]
I am unassigning this as there has been no progress in the last 5 days. This is now open!

**Comment by bishalbera** [comment]
assign it to me plz :)
