### ISSUE TITLE
GitHub Insights Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#26]
### Deriving Insights from GitHub Repositories.

Extract repository, commit, and pull request data from GitHub using Airbyte, transform it using dbt, and analyze to gain insights into code quality, collaboration patterns, and project health.

**Comment by utsavbhattarai007** [comment]
Hi @ThaliaBarrera, I am beginner in Airbyte but I am eager to learn and make quickstart of it. Would you assign to me?

**Comment by ThaliaBarrera** [comment]
Sure @utsavbhattarai007 I have assigned it to you! You can take a look at the examples and ask questions if you're in doubt!

**Comment by ThaliaBarrera** [comment]
Hi @utsavbhattarai007, this message is just to remind you that according to the Hackathon rules you have 5 days to submit progress on the issue. I’ll give you a couple more days to submit a PR, otherwise I’ll have to mark the issue as “To be Claimed” or reassign it. 

Thank you for understanding! Let me know if you have any questions.

**Comment by ThaliaBarrera** [comment]
Thanks for the update @utsavbhattarai007! Let me know if you have any questions. 

If there’s no progress in a couple of days I may need to mark it as “To be Claimed”.
