### ISSUE TITLE
Infrastructure Monitoring Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#28]
### Monitoring Infrastructure Health with Datadog Data.

Integrate infrastructure monitoring data from Datadog using Airbyte, transform the data with dbt, and create dashboards to monitor system health and performance.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by promiselxg** [comment]
I wish to work on this project, can it be assigned to me?

**Comment by ThaliaBarrera** [comment]
Hi @promiselxg! Sure, I have assigned it to you.

**Comment by btkcodedev** [comment]
@ThaliaBarrera could I try to work on this, as it's been a while after assignment? 
Cc: @promiselxg 🙂

**Comment by promiselxg** [comment]
No problem 👍

**Comment by btkcodedev** [comment]
@ThaliaBarrera, Iam not new to Airbyte, but confused how to start? Where to start, how to check?
Is there any tutorial or doc for creating quickstarts? Could you help?

**Comment by btkcodedev** [comment]
Let me comment the things which I know, This issue is for creating quickstart with
Airbyte, dbt, Datadog and Postgress with Apache superset dashboards right?

**Comment by ThaliaBarrera** [comment]
Hi @btkcodedev I suggest starting by checking out the README of this repo, and then the quickstart examples. You can also take a look at the pull requests that have been recently merged. I suggest even implementing one of the quickstarts, for example, the e-commerce analytics one. Let me know if you still have questions!

**Comment by btkcodedev** [comment]
Umm.. Blocker here, Terraform provider has no Datadog integrations available (Ref: https://github.com/airbytehq/terraform-provider-airbyte)

**Comment by ThaliaBarrera** [comment]
Sorry about that @btkcodedev, I didn’t realize it. Yes, I have assigned you to another issue in the meantime 😄

**Comment by ThaliaBarrera** [comment]
Closing this issue given the Terraform provider current limitations with Datadog.
