### ISSUE TITLE
Customer Satisfaction Analysis Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#33]
### Optimizing Customer Satisfaction with Zendesk Data.

Extract support ticket data from Zendesk using Airbyte, transform it using dbt, and analyze customer satisfaction scores and feedback to identify areas for improvement and enhance customer experience.

**Comment by MaryAyobami** [comment]
@ThaliaBarrera  I would love to work on this...can it be assigned to me?

**Comment by ThaliaBarrera** [comment]
Hi @MaryAyobami! We recommend that you work on one issue at a time. Once you've submitted a PR for the issue you have currently assigned, I can assign this one to you.

**Comment by abhiprojectz** [comment]
@ThaliaBarrera  I would like to work on this issue, Can you please assign it to me ?

**Comment by Bennykillua** [comment]
Hi @abhiprojectz I would like to work on this. Can this be assigned to me?

**Comment by ThaliaBarrera** [comment]
Hi @abhiprojectz! I have assigned it to you.

**Comment by ThaliaBarrera** [comment]
Hi @Bennykillua! Maybe you can select another issue? Or if you have experience with this type of stack, let me know and I can create a variation of this for you to contribute.

**Comment by bishalbera** [comment]
Hey @ThaliaBarrera I'm pretty new to this Data architecture thing and I'm enjoying learning it :D . So I was testing this and wanted to ask should I only include  streams like  `users, satisfaction_ratings, tickets and ticket related streams ` or should I include every streams ?? Ty :)

**Comment by ThaliaBarrera** [comment]
Hi @abhiprojectz, this message is just to remind you that according to the Hackathon rules you have 5 days to submit progress on the issue. I’ll give you a couple more days to submit a PR, otherwise I’ll have to mark the issue as “To be Claimed” or reassign it. 

Thank you for understanding! Let me know if you have any questions.

**Comment by ThaliaBarrera** [comment]
Hi @bishalbera, in general,  you can include as many streams as you consider necessary to make an interesting use case. I recommend not working on an issue until I assigned it to you. If you’re advanced with it, I can create a new Zendesk issue for you. Let me know!

**Comment by bishalbera** [comment]
@ThaliaBarrera I'm facing this same [issue](https://github.com/airbytehq/airbyte/discussions/30409) .
I have also told this to Justin Chau who is from the airbyte team and he told me he'll look into this. So what should i do now :/

**Comment by bishalbera** [comment]
@ThaliaBarrera Ya sure I will use the Airbyte UI.

**Comment by bishalbera** [comment]
@ThaliaBarrera Hello just made a [PR](https://github.com/airbytehq/quickstarts/pull/54) . As I'm pretty new into this please review it and tell me if I can do any changes. Thanks :)
