### ISSUE TITLE
Ticket Volume Analysis Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#34]
### Analyzing Support Ticket Volume with Zendesk Data.

Leverage Airbyte to extract ticket data from Zendesk, transform the data using dbt, and analyze ticket volumes, patterns, and trends to optimize support operations and resource allocation.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by Susmita-Dey** [comment]
Hey @ThaliaBarrera I wanna give it a try to solve it. Kindly assign it to me.

**Comment by ThaliaBarrera** [comment]
Hi @Susmita-Dey! Sure, I have assigned you to it.

**Comment by ThaliaBarrera** [comment]
Hi @Susmita-Dey, this message is just to remind you that according to the Hackathon rules you have 5 days to submit progress on the issue. I’ll give you a couple more days to submit a PR, otherwise I’ll have to mark the issue as “To be Claimed” or reassign it. 

Thank you for understanding! Let me know if you have any questions.

**Comment by ShatilKhan** [comment]
Hi, please assign me the issue, I'd like to contribute

**Comment by ThaliaBarrera** [comment]
Hi @ShatilKhan! We recommend that you work in one issue at a time. Once you submit a PR, I can assign you to other issues 😃

**Comment by bishalbera** [comment]
@ThaliaBarrera Hey I have submitted my PR. And next I want to work on this issue as the source is same (zendesk). So could you please check my PR . Ty :)

**Comment by ThaliaBarrera** [comment]
Sure @bishalbera, I have assigned this issue to you. Checking your PR as well!

**Comment by bishalbera** [comment]
@ThaliaBarrera should I also try to Implement Looker  for visualization?
