### ISSUE TITLE
ELT Simplified Stack

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/quickstarts#43]
Extract data from a popular source with Airbyte, load it into a data warehouse, and perform some essential transformations using dbt.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

**Comment by btkcodedev** [comment]
Is this quickstart could use any source and destination with some dbt transformations right,
If yes I would like to take this issue.
(Ps: Raised PR to NoSQL quickstart)

**Comment by ThaliaBarrera** [comment]
Yes @btkcodedev, you can use your creativity to design a nice use case with any source, destination and transformations.

**Comment by ThaliaBarrera** [comment]
@btkcodedev just checking if you're still working on this. Let me know, otherwise I may need to reassign.

**Comment by btkcodedev** [comment]
Yes, Will raise PR soon

**Comment by btkcodedev** [comment]
Raised PR #71
